# Generated by Django 5.1 on 2024-11-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('creditos1', models.PositiveSmallIntegerField()),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('provedor_id', models.CharField(max_length=100)),
            ],
        ),
    ]
